package com.metis.bubble.model;

import com.metis.bubble.model.base.BaseProjectInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectInfo extends BaseProjectInfo<ProjectInfo> {
	
}
