package com.metis.bubble.model;

import com.metis.bubble.model.base.BaseProjectMat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectMat extends BaseProjectMat<ProjectMat> {
	
}
