package com.metis.bubble.model;

import com.metis.bubble.model.base.BaseRegionSales;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionSales extends BaseRegionSales<RegionSales> {
	
}
