package com.metis.bubble.model;

import com.metis.bubble.model.base.BaseRegionSalesStats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionSalesStats extends BaseRegionSalesStats<RegionSalesStats> {
	
}
